apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: terraforge-certificate
spec:
  secretName: terraforge-tls-secret  # Name of the Kubernetes Secret to store the TLS certificate
  issuerRef:
    name: letsencrypt-staging  # Name of your Issuer or ClusterIssuer
    kind: ClusterIssuer  # Set to "Issuer" if it's not a ClusterIssuer

  #note this will have to be changed for the actual ip of the ingress
  commonName: terraforge.20.242.226.26.nip.io  # Common Name (CN) for the certificate
  dnsNames:
    - terraforge.20.242.226.26.nip.io  # Additional DNS names (SANs) for the certificate